version: '2'
services:
    pyramid-app:
        image: pyramid
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pyramid-postgresql:5432/pyramid
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pyramid-postgresql:
        extends:
            file: postgresql.yml
            service: pyramid-postgresql
